version: "3"

services:
  user-service:
    build: ./user_service
    ports:
      - "8001:8000"
    volumes:
      - ./user_service:/app
    depends_on:
      - db
    env_file:
      - .env

  product-service:
    build: ./product_service
    ports:
      - "8002:8000"
    volumes:
      - ./product_service:/app
    depends_on:
      - db
    env_file:
      - .env

  email-service:
    build: ./email_service
    volumes:
      - ./email_service:/app
    ports:
      - "8003:8000"
    depends_on:
      - redis
    env_file:
      - .env

  email-worker:
    build: ./email_service
    command: celery -A email_service worker --loglevel=info
    volumes:
      - ./email_service:/app
    depends_on:
      - email-service
      - redis
    env_file:
      - .env

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"

      
volumes:
  postgres_data:
