version: "3.9"

services:
  user-service:
    build: ./user_service
    ports:
      - "8001:8000"
    volumes:
      - ./user_service:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  product-service:
    build: ./product_service
    ports:
      - "8002:8000"
    volumes:
      - ./product_service:/app
    depends_on:
      - db
    env_file:
      - .env
    restart: always

  email-service:
    build: ./email_service
    volumes:
      - ./email_service:/app
    ports:
      - "8003:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    restart: always

  email-worker:
    build: ./email_service
    command: >
      sh -c "sleep 10 && 
             python manage.py migrate &&
             celery -A email_service.celery_app worker --loglevel=info"
    volumes:
      - ./email_service:/app
    depends_on:
      - email-service
      - redis
      - db
    env_file:
      - .env
    restart: always

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data: